name: Update README

on:
  schedule:
    - cron: "0 0 * * *"     # Daily at midnight UTC
    - cron: "37 13 * * *"   # Bonus: at 13:37 UTC (leet time 😎)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run update script
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README [skip ci]" || echo "No changes"
          git push
